### ISSUE TITLE
uninitialized constant WillPaginateSemanticUi::ActionView

### ISSUE THREAD

**Issue by ghost** [rafaelbiriba/will_paginate_semantic_ui#2]
> 
> NameError in News#index
> Showing /home/kovirolik/RubymineProjects/lol/app/views/news/index.html.erb where line #5 raised:
> uninitialized constant WillPaginateSemanticUi::ActionView
> Extracted source (around line #5):
> <%= will_paginate @news, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
> Rails.root: /home/kovirolik/RubymineProjects/lol
> 

Any way to fix it?

**Comment by rafaelbiriba** [comment]
Can you provide more details ?

Which gem version are you using ? Are you using bundler ? Looks like the gem was not required correctly.

Try to require it manually `require "will_paginate_semantic_ui"`

**Comment by rafaelbiriba** [comment]
ping

**Comment by rafaelbiriba** [comment]
No updates! Closing the issue.

Please, let me know if the problem happens again.
